### ISSUE TITLE
test should fail if the test throws

### ISSUE THREAD

**Issue by aaronblohowiak** [cloudkick/whiskey#16]
this wil timeout, instead of failing:

```
exports["test failure"] = function(test, assert){
  throw "blaaaaah";
  assert.ok(true);
  test.finish();
}
```

While i agree that we should use assert instead of throw, it makes developing tests more of a pain in the ass.

**Comment by pquerna** [comment]
+1

**Comment by Kami** [comment]
The test you have posted will be properly reported as a failure, because it's a normal "sync" test.

Something like this would be reported as a timeout if you don't use the `--sequential` option.

``` javascript
exports["test failure"] = function(test, assert){
    setTimeout(function() {
      throw "blaaaaah";
     test.finish();
   }, 200);
 assert.ok(true);
}
```

The problem with this is that if you run tests in parallel (`--concurrency` > 1) and you don't use a custom assert object which gets passed to each test function, I can't figure out to which test the exception belongs so the test is reported as "timed out" and the exception is reported as "uncaught".

If you want such tests to be properly reported as failures, you need to use `--sequential` option. This option tells the runner to only run a single test at once.

**Comment by aaronblohowiak** [comment]
Ok, i could have sworn last night that the synchronous version _was_ timing
out and not failing, but I can't reproduce this morning... If I have the
issue come up again, I will isolate it.  (I haven't done any async tests
using whiskey yet.)
- Aaron

**Comment by Kami** [comment]
Yeah, please do let me know if the issue comes up again, because then it's a bug :)
