### ISSUE TITLE
Better Test Debugging Experience

### ISSUE THREAD

**Issue by pquerna** [cloudkick/whiskey#19]
Hi,

When we have a test failure, it is very difficult to debug why a test is failing.

In traditional frameworks, you could add a debugger; statement inline a test and continue from there.

But since whiskey is spawning a subprocess, and doing more magic, this debugger statement doesn't work.

Maybe we need a `whiskey-single-malt` which runs in a single process (the parent) and lets you use the debugger on a single test file?

(or we need a better plan in general for debugging failing test cases)

**Comment by Kami** [comment]
Yes, ideally we would support V8 debugger.

I was thinking about adding a `--debug` option which would spawn a test process with `--debug` option and then immediately connect to the debugger and create a breakpoint on the first line of a test file.

The problem with this approach is that only a single client can be connected to the debugger at once. As soon as I connect to the debugger to set the breakpoint you won't, for example be able to use node-inspector. I also can't disconnect after the breakpoint has been set, because this means the breakpoint wil be lost.

I can only think of two possible solutions and both of them seem overly complex imo.
1. Create a proxy to which the user would connect with the node-inspector instead of directly connecting to the debugger. This proxy would forward all the requests sent by the node-inspector to the debug client started by Whiskey...
2. When a user uses `--debug` option, start a command line debugger, set a breakpoint on the first line of the test file and allow user to use the debugger as he would if he would use `node debug`.

Anyone has a better suggestion how I could handle this?

**Comment by Kami** [comment]
Oh, right, I could add `--debug` option which would just start test process with the `--debug-brk` option.

The problem is that this is not useful because this breakpoint will be set on the first line of the `run_test_file.js` and not in your test file.

In this case you can connect to the debugger using node-inspector, but the test file won't be listed in the file list panel so it's not useful. I could probably hack node-inspector to list the test files, but this is messy and less then ideal.

**Comment by pquerna** [comment]
I think really I just want a better way to run it in a single process -- ie,  run run_test_file.js -- I'm fine without pretty reporting during debugging as long as its clear if it failed or was successful, then I can use the the normal `node debug` and inspector without it needing extra support inside whiskey.

I'd propose then a `node debug whiskey --debug --tests=foo.js`, which would run foo.js inside your single process -- i don't care so much about the initial breakpoint being inside whiskey, thats why I'd use a debugger; statement inside my test case to break there later on.

**Comment by Kami** [comment]
OK, Whiskey 0.4.0 now has a `--debug` option.
